name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust version as needed

      - name: Install ALSA Development Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev  # Install ALSA development libraries

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 simpleaudio
          
      - name: Run Booking Checker in Loop (30s interval)
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          for i in {1..10}  # Runs 10 times (~5 minutes)
          do
            python telegram_bot.py
            echo "Waiting 30 seconds before next check..."
            sleep 30
          done