name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust version as needed

      - name: Install ALSA Development Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev  # Install ALSA development libraries

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 simpleaudio
